---

- name: Create user
  user:
    name: "{{ consul_user }}"
    home: "{{ consul_home_dir }}"
    create_home: yes
    system: yes

- set_fact:
    consul_bin_dir: "{{ consul_home_dir }}/bin"
  tags: always

- set_fact:
    consul_data_dir: "{{ consul_config.data_dir }}"

- name: Create directories
  file:
    path: "{{ item }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    state: directory
  with_items:
    - "{{ consul_home_dir }}"
    - "{{ consul_conf_dir }}"
    - "{{ consul_data_dir }}"
    - "{{ consul_pid_dir }}"
    - "{{ consul_bin_dir }}"
    - "{{ consul_acl_dir }}"

- set_fact:
    consul_work_dir: "{{ consul_home_dir }}/versions/{{ consul_version }}"
  tags: always

- name: Check if version is already installed
  stat:
    path: "{{ consul_work_dir }}/consul"
  register: consul

- name: Install Consul
  when: not consul.stat.exists
  block:
  - name: create version dir
    file:
      state: directory
      path: "{{ consul_work_dir }}"
      owner: "{{ consul_user }}"
      group: "{{ consul_group }}"

  - name: Download consul
    get_url:
      url: "{{ consul_base_url }}/consul_{{ consul_version }}_linux_amd64.zip"
      dest: "/tmp/consul.{{ consul_version }}.zip"
      owner: "{{ consul_user }}"
      group: "{{ consul_group }}"
      remote_src: yes

  - name: Unarchive consul
    unarchive:
      src: "/tmp/consul.{{ consul_version }}.zip"
      dest: "{{ consul_work_dir }}"
      owner: "{{ consul_user }}"
      group: "{{ consul_group }}"
      remote_src: yes

- name: Create link to current version
  file:
    src: "{{ consul_work_dir }}/consul"
    path: "{{ consul_bin_dir }}/consul"
    state: link

- name: Create link to current version in bin dir
  file:
    src: "{{ consul_bin_dir }}/consul"
    path: /usr/local/bin/consul
    state: link

