---

- name: Install
  tags:
  - install
  block:
  - name: install required packages
    package:
      name: "{{ item }}"
      state: present
    loop:
    - unzip

  - name: Install consul
    import_tasks: install.yml
    tags: install

- import_tasks: configure.yml
  tags: config

- name: Configure Consul Services
  import_tasks: service.yml
  tags: services
  when: consul_services is defined
