---

- name: Install
  tags:
  - install
  block:
  - name: install required packages
    package:
      name: "{{ item }}"
      state: present
    loop:
    - unzip

  - name: Install consul
    import_tasks: install.yml

- name: Configure
  tags:
  - config
  block:
  - name: Configure consul
    import_tasks: configure.yml

  - name: Create systemd Unit File
    template:
      src: consul.systemd.j2
      dest: /etc/systemd/system/consul.service
    notify:
    - systemctl daemon-reload
