---

- name: systemctl daemon-reload
  systemd:
    daemon_reload: True

- name: systemctl restart consul
  systemd:
    name: consul.service
    state: restarted
    enabled: yes
  when: consul_manage_service and consul_restart_on_change

