---

- name: Get Token Secret
  uri:
    url: "{{ consul_schema }}://{{ consul_host }}:{{ consul_port }}/v1/acl/token/{{ acl_tokens.get(item.value) }}"
    method: GET
    headers:
      X-Consul-Token: "{{ consul_token }}"
      Content-Type: application/json
  register: r_secret
  run_once: true

- set_fact:
    secrets: "{{ secrets | default({}) | combine({item.key: r_secret.json.SecretID}) }}"

