---

- name: Gather Tokens
  uri:
    url: "{{ consul_schema }}://{{ consul_host }}:{{ consul_port }}/v1/acl/tokens"
    method: GET
    headers:
      X-Consul-Token: "{{ consul_token }}"
      Content-Type: application/json
  register: r_tokens
  run_once: true

- name: Generate ACL Token fact
  set_fact:
    acl_tokens: "{{ acl_tokens | default({}) | combine({item.0: item.1}) }}"
  loop: "{{ r_tokens.json | default([]) | json_query('[*].[Description, AccessorID]') }}"

